artifacts_root: artifacts  

data_ingestion:
  root_dir: artifacts/data_ingestion
  customers_data: data/customers.csv
  loans_data: data/loans.csv
  bureau_data: data/bureau_data.csv
  output_path: artifacts/data_ingestion/data.csv

data_preprocessing:
  root_dir: artifacts/data_preprocessing
  input_data: artifacts/data_ingestion/data.csv
  output_data: artifacts/data_preprocessing/preprocessed_data.csv

data_cleaning:
  root_dir: artifacts/data_cleaning
  input_filepath: artifacts/data_preprocessing/preprocessed_data.csv
  test_path: artifacts/data_cleaning/test_data.arr
  train_path: artifacts/data_cleaning/train_data.arr
  model_path : artifacts/data_cleaning/preprocessor.joblib
  target_column: default

model_training:
  root_dir: artifacts/model_training
  train_path: artifacts/data_cleaning/train_data.arr
  test_path: artifacts/data_cleaning/test_data.arr
  preprocessor: artifacts/model_training/preprocessor.joblib
  model_path : artifacts/model_training/best_model.joblib












classification_metric:
  preprocessor: artifacts/model_training/preprocessor.joblib
  model_path : artifacts/model_training/best_model.joblib